### ISSUE TITLE
Compilation error in file lib/scout_apm/logger.ex

### ISSUE THREAD

**Issue by cpursley** [scoutapp/scout_apm_elixir#86]
I'm getting the following strange issue when compiling my Pheonix app:

```
==> scout_apm
Compiling 55 files (.ex)

== Compilation error in file lib/scout_apm/logger.ex ==
** (FunctionClauseError) no function clause matching in Keyword.fetch/2

    The following arguments were given to Keyword.fetch/2:

        # 1
        {:metadata, [line: 46], nil}

        # 2
        :application

    Attempted function clauses (showing 1 out of 1):

        def fetch(+keywords+, +key+) when -is_list(keywords)- and +is_atom(key)+

    (elixir) lib/keyword.ex:362: Keyword.fetch/2
    (logger) lib/logger.ex:829: anonymous fn/4 in Logger.compile_time_purge_matching?/2
    (elixir) lib/enum.ex:2850: Enum.all_list/2
    (elixir) lib/enum.ex:2864: Enum.any_list/2
    (logger) lib/logger.ex:800: Logger.macro_log/4
    (logger) expanding macro: Logger.log/3
    lib/scout_apm/logger.ex:46: ScoutApm.Logger.log/3
could not compile dependency :scout_apm, "mix compile" failed. You can recompile this dependency with "mix deps.compile scout_apm", update it with "mix deps.update scout_apm" or clean it with "mix deps.clean scout_apm"
```

elixir 1.7.3
phoenix 1.3.4
scout_apm: 0.4.14

**Comment by cpursley** [comment]
Closing. This was caused by a bug in elixir 1.7.3.
